_wandb:
    value:
        cli_version: 0.24.0
        e:
            y2svkocew9db7f919h3y3hg734mal91j:
                args:
                    - config/basic.py
                codePath: ..\comp560-nanoGPT\train.py
                codePathLocal: ..\..\comp560-nanoGPT\train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "874963267584"
                        used: "651721011200"
                email: kollanishanth01@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: 279c70a210dbac9a435f6c6aaf288de695a79aa5
                    remote: https://github.com/nishcola/comp560-nishkolla.git
                gpu: NVIDIA GeForce GTX 1650 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1280
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 SUPER
                      uuid: GPU-43203ced-0961-3d63-e815-a90e25372636
                host: DESKTOP-N8576GD
                memory:
                    total: "34147999744"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Nish\Documents\comp560-nanoGPT\train.py
                python: CPython 3.13.2
                root: C:\Users\Nish\Documents\comp560-nishkolla\alphabet
                startedAt: "2026-01-28T03:26:39.321029Z"
                writerId: y2svkocew9db7f919h3y3hg734mal91j
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.13.2
            "5": 0.24.0
            "8":
                - 3
            "12": 0.24.0
            "13": windows-amd64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 64
compile:
    value: false
dataset:
    value: basic
decay_lr:
    value: true
device:
    value: cpu
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 50
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 2
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out
wandb_log:
    value: true
wandb_project:
    value: nish-alphabet
wandb_run_name:
    value: alphabet
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
